version: '3'

services:
  postgres:
    image: postgres:15-bookworm
    container_name: test-unibuddy-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test-unibuddy-db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/backup

volumes:
  postgres_data: