spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-unibuddy-db
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

entity:
  exists: "entity already exists in the database."
  notnull: "entity should not be null"
  info:
    notvalid: "profile info is not valid. check required fields: [nickname, email, dateOfBirth, country]"
#todo: which fields should be required? phone auth l8r on?