openapi: 3.0.0
info:
  title: Uni Buddy API
  description: API for managing user profiles in Uni Buddy application
  version: 1.0.0
tags:
  - name: Profile
  - name: Auth
paths:
  /public/welcome:
    get:
      operationId: welcome
      tags:
        - Profile
      summary: Get welcome message
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /auth/signup:
    post:
      summary: Sign Up
      description: Register a new user.
      operationId: signUp
      tags:
        - Auth
      requestBody:
          $ref: '#/components/requestBodies/LoginReqRes'
      responses:
        '200':
          $ref: '#/components/responses/LoginReqRes'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal server error
  /auth/signin:
    post:
      summary: Sign In
      description: Authenticate and sign in a user.
      operationId: signIn
      tags:
        - Auth
      requestBody:
        $ref: '#/components/requestBodies/LoginReqRes'
      responses:
        '200':
          $ref: '#/components/responses/LoginReqRes'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal server error
  /auth/refresh:
    post:
      summary: Refresh Token
      description: Refresh the authentication token.
      operationId: refreshToken
      tags:
        - Auth
      requestBody:
        $ref: '#/components/requestBodies/LoginReqRes'
      responses:
        '200':
          $ref: '#/components/responses/LoginReqRes'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal server error
  /admin/profile/create:
    post:
      operationId: createProfile
      tags:
        - Profile
      summary: Create a new profile
      requestBody:
        $ref: '#/components/requestBodies/ProfileRequestBody'
      responses:
        '201':
          $ref: '#/components/responses/ProfileResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal server error
  /user/profile:
    get:
      operationId: getProfileByNickname
      tags:
        - Profile
      summary: Get profile by nickname
      parameters:
        - in: query
          name: nickname
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ProfileResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal server error
  /user/profile/{id}:
    get:
      operationId: getProfileById
      tags:
        - Profile
      summary: Get profile by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          $ref: '#/components/responses/ProfileResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal server error
  /admin/profile/update/{id}:
    put:
      operationId: updateProfile
      tags:
        - Profile
      summary: Update profile
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        $ref: '#/components/requestBodies/ProfileRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/ProfileResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal server error
  /admin/profile/delete/{id}:
    delete:
      operationId: deleteProfile
      tags:
        - Profile
      summary: Delete profile
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No Content
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal server error
components:
  requestBodies:
    ProfileRequestBody:
      description: JSON object for profile request
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProfileRequest'
    LoginReqRes:
      description: JSON object for login request/response
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginReqRes'
  responses:
    ProfileResponse:
      description: JSON object for profile response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProfileResponse'
    LoginReqRes:
      description: JSON object for login request/response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginReqRes'
  schemas:
    AuthUser:
      $ref: './login/_index.yaml#/AuthUser'
    ProfileRequest:
      $ref: './request/_index.yaml#/ProfileRequest'
    ProfileResponse:
      $ref: './response/_index.yaml#/ProfileResponse'
    LoginReqRes:
      $ref: './login/_index.yaml#/LoginReqRes'

